application: karmelupdates
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /tasks/updatedb
  script: main.py
  
- url: /.*
  script: main.py


